config:
  deep_check: true
  ignore_module:
    - "github.com/terraform-aws-modules/*"

plugin_directory: .tflint.d/plugins

rules:
  terraform_unused_declarations: true
  terraform_comment_syntax: true
  terraform_naming_convention: true
