name: Terragrunt Plan & Apply
 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terragrunt-plan-apply:
    runs-on: ubuntu-latest
    env:
      GITHUB_APP_PEM: ${{ secrets.APP_PEM }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
      GITHUB_APP_ID: ${{ secrets.APP_ID }}
      GITHUB_OWNER: "Platform-management"
      GITHUB_APP_PEM_FILE: ${{ github.workspace }}/app.pem

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.12/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Write GitHub App PEM to root
        run: echo "$GITHUB_APP_PEM" > ./app.pem
      

      - name: Check env vars
        run: |
          echo "GITHUB_OWNER=$GITHUB_OWNER"
          echo "GITHUB_APP_ID=$GITHUB_APP_ID"
          echo "GITHUB_APP_INSTALLATION_ID=$GITHUB_APP_INSTALLATION_ID"
          echo "GITHUB_APP_PEM_FILE exists: $(test -f $GITHUB_APP_PEM_FILE && echo yes || echo no)"

      - name: Terragrunt Init
        working-directory: ./live
        run: terragrunt run-all init
        env:
          GITHUB_OWNER: ${{ env.GITHUB_OWNER }}
          GITHUB_APP_ID: ${{ env.GITHUB_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ env.GITHUB_APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: ${{ env.GITHUB_APP_PEM_FILE }}

      - name: Terragrunt Plan
        working-directory: ./live
        run: terragrunt run-all plan -out=plan.tfplan
        env:
          GITHUB_OWNER: ${{ env.GITHUB_OWNER }}
          GITHUB_APP_ID: ${{ env.GITHUB_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ env.GITHUB_APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: ${{ env.GITHUB_APP_PEM_FILE }}

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./live
        run: terragrunt run-all apply --terragrunt-non-interactive -auto-approve plan.tfplan
        env:
          GITHUB_OWNER: ${{ env.GITHUB_OWNER }}
          GITHUB_APP_ID: ${{ env.GITHUB_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ env.GITHUB_APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: ${{ env.GITHUB_APP_PEM_FILE }}
