name: Terragrunt Plan & Apply
 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terragrunt-plan-apply:
    runs-on: ubuntu-latest
    env:
      GITHUB_APP_PEM: ${{ secrets.APP_PEM }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
      GITHUB_APP_ID: ${{ secrets.APP_ID }}
      GITHUB_OWNER: "Platform-management"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.12/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Write GitHub App PEM to root
        run: | 
          cat <<'EOF' > app.pem
          $GITHUB_APP_PEM
          EOF
          chmod 600 app.pem
        shell: bash

      - name: Generate GitHub App JWT
        run: |
          ls -la .

      - name: dir
        working-directory: ./live
        run: ls -la .

      - name: Terragrunt Init
        working-directory: ./live
        run: terragrunt run-all init

      - name: Terragrunt Plan
        working-directory: ./live
        run: terragrunt run-all plan -out=plan.tfplan

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./live
        run: terragrunt run-all apply --terragrunt-non-interactive -auto-approve plan.tfplan
